core/urls.py
from django.conf import settings
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import (
	PasswordResetConfirmView,
	PasswordResetDoneView,
	PasswordChangeView,
	PasswordResetView,
	LogoutView
)

from .forms import CustomUserForm
from core import views

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('products/', views.ProductListView.as_view(), name='products'),
	path('product/<slug:slug>/', views.ProductPageView.as_view(), name='one_product'),
	path('add_product/<slug:slug>/', views.AddProductView.as_view(), name='add_product'),
	path('add_product_list/', views.AddProductListView.as_view(), name='add_product_list'),
	path('personal_account/', views.PersonalAccountView.as_view(), name='personal_account'),
	path('product_update/<product_id>/', views.ProductUpdateView.as_view(), name='product_update'),
	path('proposals/<order_id>/', views.OrderExecutionProposalView.as_view(), name='proposals'),
	path('become_company/', views.BecomeCompanyView.as_view(), name='become_company'),
	path('update_company/', views.BecomeCompanyView.as_view(), name='update_company'),
	path('shopping_cart/', views.ShoppingCartView.as_view(), name='shopping_cart'),
	path('admin_panel/', views.AdminPanelView.as_view(), name='admin_panel'),
	path('new_orders/', views.NewOrdersView.as_view(), name='new_orders'),
	path('orders/', views.OrdersListView.as_view(), name='orders'),
	path('login/', views.LoginView.as_view(), name='login'),

	path('ordering/', views.OrderingView.as_view(), name='ordering'),
	path('product_distribution/', views.ProductDistributionView.as_view(), name='product_distribution'),
	path('order_handler/<ord_exec_id>/', views.set_order_status_view, name='order_handler'),
	path('cancel_order/<order_id>/<context>/', views.cancel_order_view, name='cancel_order'),
	path('delete_notification/', views.delete_notification_view, name='delete_notification'),
	path('choose_offer/<order_id>/<offer>/', views.choose_offer_view, name='choose_offer'),
	path('split_order/<order_id>/<offer>/', views.split_order_view, name='split_order'),
	path('repeat_order/<order_id>/', views.repeat_order_view, name='repeat_order'),
	path('payment/<order_id>/', views.PaymentView.as_view(), name='payment'),
	path('inn_search/<inn>/', views.inn_search_view, name='inn_search'),

	path('help/', TemplateView.as_view(template_name='other_pages/help.html'), name='help'),
	path('about_us/', TemplateView.as_view(template_name='other_pages/about_us.html'), name='about_us'),
	path('city_selection/', views.city_selection_view, name='city'),

	path('policy/platform', TemplateView.as_view(template_name='other_pages/policy/platform.html'), name='platform'),
	path('policy/privacy', TemplateView.as_view(template_name='other_pages/policy/privacy.html'), name='privacy'),
	path('policy/service', TemplateView.as_view(template_name='other_pages/policy/service.html'), name='service'),
	path('policy/p_data', TemplateView.as_view(template_name='other_pages/policy/p_data.html'), name='p_data'),
	path('policy/', TemplateView.as_view(template_name='other_pages/privacy_policy.html'), name='policy'),

	path('create_product/', views.create_product_view),

	path(
		'become_company_fail/',
		TemplateView.as_view(
			template_name='account_pages/become_company_fail.html'
		),
		name='become_company_fail'),

	path(
		'delete_product_in_cart/<product_id>/',
		views.delete_product_in_cart_view,
		name='delete_product_in_cart'
	),

	path(
		'password_reset/',
		PasswordResetView.as_view(
			template_name='account_pages/password_reset.html',
			email_template_name='account_pages/password_reset_body.txt',
			subject_template_name='account_pages/password_reset_subject.txt'
		),
		name='password_reset'
	),

	path(
		'password_reset_done/',
		PasswordResetDoneView.as_view(
			template_name='account_pages/password_reset_done.html',
		),
		name='password_reset_done'
	),

	path(
		'password_reset_confirm/<uidb64>/<token>/',
		PasswordResetConfirmView.as_view(
			template_name='account_pages/password_reset_confirm.html',
			success_url='/login/'
		),
		name='password_reset_confirm'
	),

	path(
		'password_change/',
		PasswordChangeView.as_view(
			template_name='account_pages/password_change.html',
			success_url='/personal_account/'
		),
		name='password_change'
	),

	path(
		'logout/',
		LogoutView.as_view(),
		{'next_page': settings.LOGOUT_REDIRECT_URL},
		name='logout'
	),

	path(
		'account/register/',
		RegistrationView.as_view(form_class=CustomUserForm),
		name='register'
	),

	path('account/', include('django_registration.backends.activation.urls')),
]

printoplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from phonenumber_field.modelfields import PhoneNumberField


class UserManager(BaseUserManager):
	def create_user(
		self, email, first_name, last_name, is_receiving_news,
		is_company, phone_number, company_name, addresses, password=None
	):

		if not email:
			raise ValueError('У пользователя должен быть адрес электронной почты')

		user = self.model(
			email=self.normalize_email(email),
			first_name=first_name,
			last_name=last_name,
			phone_number=phone_number,
			company_name=company_name,
			addresses=addresses,
			is_receiving_news=is_receiving_news,
			is_company=is_company
		)
		user.set_password(password)
		user.save(using=self._db)

		return user

	def create_superuser(self, email, password=None):
		user = self.create_user(
			email,
			first_name='Admin',
			last_name='',
			phone_number='',
			company_name='',
			addresses=[],
			is_receiving_news=False,
			is_company=False,
			password=password
		)
		user.is_admin = True
		user.is_active = True
		user.save(using=self._db)

		return user


class User(AbstractBaseUser):
	"""Базовый класс всех пользователей"""
	email = models.EmailField(
		verbose_name='Email',
		max_length=255,
		unique=True
	)
	first_name = models.CharField(
		verbose_name='Имя',
		max_length=32
	)
	last_name = models.CharField(
		verbose_name='Фамилия',
		max_length=32
	)
	phone_number = PhoneNumberField(
		verbose_name='Номер телефона',
		max_length=12,
		blank=True,
	)
	company_name = models.CharField(
		verbose_name='Название компании',
		max_length=64,
		blank=True
	)
	addresses = models.JSONField()
	order_id = models.IntegerField(blank=True, null=True)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_receiving_news = models.BooleanField(default=False)
	is_company = models.BooleanField(default=False)
	is_active = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	def email_user(self, subject, message, from_email=None, **kwargs):
		"""Send an email to this user."""
		send_mail(subject, message, from_email, [self.email], **kwargs)

	def full_name(self):
		return '%s %s' % (self.last_name, self.first_name)

	def __str__(self):
		return self.first_name

	def has_perm(self, perm, obj=None):
		return True

	def has_perms(self, perm_list, obj=None):
		for perm in perm_list:
			if perm == 'is_auth' and not self.is_authenticated:
				return False
			if perm == 'is_admin' and not self.is_admin:
				return False
			if perm == 'is_company' and not self.is_company:
				return False
			if perm == 'is_not_company' and self.is_company:
				return False
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin


class Company(models.Model):
	"""Пользователь-исполнитель — данные о компании предоставляемой продукцию"""
	user = models.OneToOneField('User', on_delete=models.CASCADE)
	addresses = ArrayField(
		models.CharField(max_length=256),
		size=None,
		verbose_name='Список адресов'
	)
	inn = models.CharField(
		verbose_name='ИНН',
		max_length=12
	)
	logo = models.FileField(
		verbose_name='Логотип',
		upload_to='company_logos/',
		max_length=50,
		blank=True
	)
	company_files = models.FileField(
		verbose_name='Документы',
		upload_to='company_files/',
		max_length=50,
		blank=True
	)
	moderator_message = models.CharField(
		verbose_name='Сообщение для пользователя',
		max_length=256,
		blank=True
	)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_verification = models.BooleanField(default=False)
	is_verified = models.BooleanField(default=False)

	objects = models.Manager()


class Product(models.Model):
	"""Базовое описание продукта предоставляемого сайтом"""
	slug = models.SlugField(
		max_length=32,
		unique=True
	)
	name = models.CharField(
		verbose_name='Название',
		max_length=32
	)
	CATEGORY = (
		(1, 'Продукция с переплётом'),
		(2, 'Флаеры, открытки и плакаты'),
		(3, 'Календари'),
		(4, 'Офисное'),
		(5, 'Рекламная'),
		(6, 'Для гастрономии и событий'),
	)
	category = models.IntegerField(choices=CATEGORY)
	description = models.CharField(
		verbose_name='Описание',
		max_length=256
	)
	price = models.IntegerField()

	objects = models.Manager()

	def __str__(self):
		return self.name


class ProductCompany(models.Model):
	"""Продукт предоставляемый пользователем-исполнителем(компанией) на основе базового продукта"""
	company = models.ForeignKey(
		'Company',
		verbose_name='Компания',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		verbose_name='Продукт',
		on_delete=models.CASCADE
	)
	price = models.JSONField(verbose_name='Цены на продукт')
	characteristics = models.JSONField(verbose_name='Характеристики')

	objects = models.Manager()


class ShoppingCart(models.Model):
	"""Продукты находящиеся в корзине конкретного пользователя"""
	user = models.ForeignKey(
		'User',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		on_delete=models.CASCADE
	)
	characteristics = models.JSONField()
	design = models.FileField(
		upload_to='design_product/',
		max_length=50
	)
	other_design = ArrayField(
		models.FileField(
			upload_to='design_product/',
			max_length=50
		),
		size=None,
	)
	count = models.IntegerField()

	objects = models.Manager()


class ProductCharacteristics(models.Model):
	"""Список характеристик и их значений для конкретного продукта"""
	product = models.OneToOneField('Product', verbose_name='Продукт', on_delete=models.CASCADE)

	format = models.JSONField(verbose_name='Формат', null=True)
	color = models.JSONField(verbose_name='Цвет', null=True)
	material = models.JSONField(verbose_name='Материал', null=True)
	rounding = models.JSONField(verbose_name='Скругление', null=True)
	adhesive_side = models.JSONField(verbose_name='Клейкая сторона', null=True)
	sheets_count = models.JSONField(verbose_name='Количество листов', null=True)
	sheets_arrangement = models.JSONField(verbose_name='Расположение листов', null=True)
	protective_film = models.JSONField(verbose_name='Защитная плёнка', null=True)
	spiral_color = models.JSONField(verbose_name='Цвет спирали', null=True)
	finishing = models.JSONField(verbose_name='Отделка', null=True)
	paper = models.JSONField(verbose_name='Бумага', null=True)

	objects = models.Manager

	def __str__(self):
		return self.product.__str__()


class Order(models.Model):
	"""Базовая модель заказа"""
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	price = models.IntegerField(verbose_name='Общая стоимость')

	objects = models.Manager


class OrderDetail(models.Model):
	"""Детальное описание заказа после его оформления"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	address_and_deadline = models.JSONField(verbose_name='Адреса доставки и сроки')
	comment = models.CharField(
		verbose_name='Комментарий',
		max_length=1024,
		blank=True
	)
	datetime = models.DateTimeField(auto_now_add=True)
	STATUS = (
		(0, 'Формирование заказа'),
		(1, 'Новый заказ'),
		(2, 'Ожидания взятия в работу'),
		(3, 'Взят в работу'),
		(4, 'Ожидание подтверждения'),
		(5, 'Исполнен'),
		(6, 'Удалён')
	)
	status = models.IntegerField(choices=STATUS)

	objects = models.Manager


class OrderProduct(models.Model):
	"""Продукты фигурирующие в заказе"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	product = models.ForeignKey('Product', on_delete=models.CASCADE)
	characteristics = models.JSONField(verbose_name='Характеристики')
	design_url = models.CharField(verbose_name='Ссылка на дизайн', max_length=128)
	other_design_url = ArrayField(models.CharField(max_length=128), size=None)
	total_count = models.IntegerField(verbose_name='Общее количество товара')
	price = models.IntegerField(verbose_name='Стоимость')
	# {'ID_адреса': Количество, ...}
	count_and_address = models.JSONField(verbose_name='Адреса доставки и количество товара')

	objects = models.Manager


class OrderExecutionProposal(models.Model):
	"""Предложения от компаний на выполнение заказа"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	# {'ID_продукта': (Количество, ID_адреса, Цена), ...}
	order_products = models.JSONField()
	price = models.IntegerField(verbose_name='Общая стоимость предложения')
	is_paid = models.BooleanField(verbose_name='Статус оплаты для размещения предложения', default=False)
	is_partially = models.BooleanField(verbose_name='Частичное выполнение', default=False)

	objects = models.Manager


class OrderProposalTemp(models.Model):
	"""Временное сохранение списка предложений"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	proposal = models.JSONField()
	count = models.IntegerField(verbose_name='Количество предложений на один заказ')

	objects = models.Manager


class OrderExecution(models.Model):
	"""Заказ на выполнение компанией каторую выбрал заказчик"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	order_products = models.JSONField()
	STATUS = (
		(2, 'Отправлен на исполнение'),
		(3, 'Взят в работу'),
		(4, 'Подтверждение получения'),
		(5, 'Исполнен'),
		(6, 'Отменён')
	)
	status = models.IntegerField(choices=STATUS)
	price = models.IntegerField(verbose_name='Стоимость')

	objects = models.Manager


class OldOrder(models.Model):
	"""Информация о недействующих заказах"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	price = models.IntegerField()
	CONTEXT = (
		(1, 'Завершён'),
		(2, 'Окончание срока'),
		(3, 'Отмена компанией'),
		(4, 'Отмена клиентом'),
	)
	context = models.IntegerField(choices=CONTEXT)

core/templates/django_registration/activation_complete.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Регистрация{% endblock %}
{% block content_class %}bg-light h-100-80{% endblock %}
{% block content %}
<!-- Registration form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Регистрация</h3>
		</div>
		<div class="d-flex justify-content-center">
			<div class="rounded border bg-white p-4">
				<p class="text-secondary text-center">Вы успешно подтвердили свой Email!</p>

				<div class="d-flex justify-content-center mt-4">
					<a href="{% url 'login' %}" class="btn btn-primary">Войти</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/django_registration/activation_email_body.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/4649526873.js" crossorigin="anonymous"></script>

    <style type="text/css">
      .bg-light {
        background-color: #f2f2f2!important;
      }
      .link-primary {
        color: #f3651b!important;
      }
      .bg-primary {
        background-color: #f3651b!important;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand link-primary" href="localhost:8000">
          <img
              src="https://raw.githubusercontent.com/max-sanch/airprint/8f9980667a69123562888e2260af884da81d98b8/image/image/logo.svg"
              width="30" height="30" class="d-inline-block align-top">
          PrintoPlace
        </a>
      </div>
    </nav>

    <div class="pb-4">
      <div class="container">
        <h5 class="pt-5">Здравствуйте, {{ user }}!</h5>
        <p class="pt-3 m-0">Регистрация на сайте PrintoPlace.</p>
        <p class="mt-0">
          Для активации вашего аккаунта необходимо перейти по
          <a href="localhost:8000/account/activate/{{ activation_key }}/" style="color: #f3651b!important;">ссылке</a>!
        </p>
        <p class="pt-3">Если вы не регистрировались на этом сайте, просто удалите сообщение!</p>
        <p class="pt-4 m-0">С уважением,</p>
        <a href="localhost:8000" style="color: #f3651b!important;">PrintoPlace</a>
      </div>
    </div>

    <div class="bg-primary">
      <div class="container pb-3">
        <div class="row">
          <div class="col-sm-7 mt-3 pr-0">
            <div class="d-flex flex-column bd-highlight">
              <div class="bd-highlight"><h5 class="text-white">Любые вопросы?</h5></div>
              <div class="bd-highlight"><p class="text-white mb-0">Проконсультируем в личной беседе.</p></div>
            </div>
          </div>
          <div class="col-sm-5 mt-3 pl-0">
            <div class="d-flex flex-column bd-highlight">
              <div class="bd-highlight ml-auto"><h5 class="text-white"><i class="fas fa-phone"></i> +7 (999) 999-9999</h5></div>
              <div class="bd-highlight ml-auto"><p class="text-white mb-0"><i class="fas fa-at"></i> Email: help@printoplace.ru</p></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div>
      <div class="container">
        <p class="text-secondary text-center mt-2">
          Это письмо отправлено автоматически. Пожалуйста, не отвечайте на него.
        </p>
      </div>
    </div>

    <!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/django_registration/activation_failed.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Ошибка активации{% endblock %}
{% block content_class %}bg-light h-100-80{% endblock %}
{% block content %}
<!-- Registration form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Ошибка активации</h3>
		</div>
		<div class="d-flex justify-content-center">
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<p class="text-secondary text-center m-0">{{ activation_error.message }}</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/django_registration/registration_closed.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Регистрация{% endblock %}
{% block content_class %}bg-light h-100-80{% endblock %}
{% block content %}
<!-- Registration form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Регистрация не доступна</h3>
		</div>
		<div class="d-flex justify-content-center">
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<p class="text-secondary text-center m-0">В данный момент регистрация не доступна!</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/django_registration/registration_complete.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Регистрация{% endblock %}
{% block content_class %}bg-light h-100-80{% endblock %}
{% block content %}
<!-- Registration form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Регистрация</h3>
		</div>
		<div class="d-flex justify-content-center">
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<p class="text-secondary text-center m-0">
					Для завершения регистрации необходимо подтвердить Email!<br>
					Проверьте свою почту, если письмо не пришло,<br>
					возможно оно находится в "Спам"
				</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/django_registration/registration_form.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Регистрация{% endblock %}
{% block content_class %}bg-light h-100-80{% endblock %}
{% block content %}
<!-- Registration form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Регистрация</h3>
		</div>
		<div class="d-flex justify-content-center">
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<form method="post">
					{% csrf_token %}
					<input type="hidden" name="next" value="">

					<div class="form-row">
						<div id="div_id_first_name" class="form-group required col-md-6">
							<label for="id_first_name" class=" requiredField">Имя<span class="asteriskField">*</span></label>
							<div class="">
								<input type="text" name="first_name" maxlength="32"
											 class="textinput textInput form-control {% if form.first_name.errors %}is-invalid{% endif %}"
											 value="{% if form.first_name.value and not form.first_name.errors %}{{ form.first_name.value }}{% endif %}"
											 required id="id_first_name">
							</div>
							{% for error in form.first_name.errors %}
							<p class="mt-1 text-danger">{{ error|escape }}</p>
							{% endfor %}
						</div>


						<div id="div_id_last_name" class="form-group required col-md-6">
							<label for="id_last_name" class="requiredField">Фамилия<span class="asteriskField">*</span></label>
							<div class="">
								<input type="text" name="last_name" maxlength="32"
											 class="textinput textInput form-control {% if form.last_name.errors %}is-invalid{% endif %}"
											 value="{% if form.last_name.value and not form.last_name.errors %}{{ form.last_name.value }}{% endif %}"
											 required id="id_last_name">
							</div>
							{% for error in form.last_name.errors %}
							<p class="mt-1 text-danger">{{ error|escape }}</p>
							{% endfor %}
						</div>
					</div>


					<div id="div_id_email" class="form-group required">
						<label for="id_email" class=" requiredField">Email<span class="asteriskField">*</span></label>
						<div class="">
							<input type="email" name="email" maxlength="255" autofocus=""
										 class="emailinput form-control {% if form.email.errors %}is-invalid{% endif %}"
										 value="{% if form.email.value and not form.email.errors %}{{ form.email.value }}{% endif %}"
										 required id="id_email">
						</div>
						{% for error in form.email.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_phone_number" class="form-group">
						<label for="id_phone_number">Номер телефона<span class="asteriskField">*</span></label>
						<div class="">
							<input type="tel" name="phone_number" maxlength="12"
										 class="textinput textInput form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
										 value="{% if form.phone_number.value and not form.phone_number.errors %}{{ form.phone_number.value }}{% endif %}"
										 required id="id_phone_number">
						</div>
						{% for error in form.phone_number.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_company_name" class="form-group">
						<label for="id_company_name">Название компании</label>
						<div class="">
							<input type="text" name="company_name" maxlength="64"
										 class="textinput textInput form-control {% if form.company_name.errors %}is-invalid{% endif %}"
										 value="{% if form.company_name.value and not form.company_name.errors %}{{ form.company_name.value }}{% endif %}"
										 id="id_company_name">
							<small class="form-text text-muted">Стать исполнителем можно будет в личном кабинете.</small>
						</div>
						{% for error in form.company_name.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_password1" class="form-group required">
						<label for="id_password1" class="requiredField">Пароль<span class="asteriskField">*</span></label>
						<div class="">
							<input type="password" name="password1" autocomplete="new-password"
										 class="textinput textInput form-control {% if form.password1.errors %}is-invalid{% endif %}"
										 required id="id_password1">
						</div>
						{% for error in form.password1.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_password2" class="form-group required">
						<label for="id_password2" class="requiredField">Подтверждение пароля<span class="asteriskField">*</span></label>
						<div class="">
							<input type="password" name="password2" autocomplete="new-password"
										 class="textinput textInput form-control {% if form.password2.errors %}is-invalid{% endif %}"
										 required id="id_password2">
						</div>
						{% for error in form.password2.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div class="form-group">
						<div id="div_id_is_receiving_news" class="form-check">
							<input type="checkbox" name="is_receiving_news" class="checkboxinput form-check-input" id="id_is_receiving_news">
							<label for="id_is_receiving_news" class="form-check-label">Я согласен на рассылку новостей</label>
						</div>
					</div>

					<div class="form-group required">
						<div class="form-check">
							<input type="checkbox" class="checkboxinput form-check-input" required>
							<label class="form-check-label">Я согласен с Политикой конфидециальности<br>и Условиями сервиса<span class="asteriskField">*</span></label>
						</div>
					</div>

					<div class="d-flex justify-content-center mt-4">
						<button type="submit" class="btn btn-primary">Зарегистрироваться</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}