core/urls.py
from django.conf import settings
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import (
	PasswordResetConfirmView,
	PasswordResetDoneView,
	PasswordChangeView,
	PasswordResetView,
	LogoutView
)

from .forms import CustomUserForm
from core import views

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('products/', views.ProductListView.as_view(), name='products'),
	path('product/<slug:slug>/', views.ProductPageView.as_view(), name='one_product'),
	path('add_product/<slug:slug>/', views.AddProductView.as_view(), name='add_product'),
	path('add_product_list/', views.AddProductListView.as_view(), name='add_product_list'),
	path('personal_account/', views.PersonalAccountView.as_view(), name='personal_account'),
	path('product_update/<product_id>/', views.ProductUpdateView.as_view(), name='product_update'),
	path('proposals/<order_id>/', views.OrderExecutionProposalView.as_view(), name='proposals'),
	path('become_company/', views.BecomeCompanyView.as_view(), name='become_company'),
	path('update_company/', views.BecomeCompanyView.as_view(), name='update_company'),
	path('shopping_cart/', views.ShoppingCartView.as_view(), name='shopping_cart'),
	path('admin_panel/', views.AdminPanelView.as_view(), name='admin_panel'),
	path('new_orders/', views.NewOrdersView.as_view(), name='new_orders'),
	path('orders/', views.OrdersListView.as_view(), name='orders'),
	path('login/', views.LoginView.as_view(), name='login'),

	path('ordering/', views.OrderingView.as_view(), name='ordering'),
	path('product_distribution/', views.ProductDistributionView.as_view(), name='product_distribution'),
	path('order_handler/<ord_exec_id>/', views.set_order_status_view, name='order_handler'),
	path('cancel_order/<order_id>/<context>/', views.cancel_order_view, name='cancel_order'),
	path('delete_notification/', views.delete_notification_view, name='delete_notification'),
	path('choose_offer/<order_id>/<offer>/', views.choose_offer_view, name='choose_offer'),
	path('split_order/<order_id>/<offer>/', views.split_order_view, name='split_order'),
	path('repeat_order/<order_id>/', views.repeat_order_view, name='repeat_order'),
	path('payment/<order_id>/', views.PaymentView.as_view(), name='payment'),
	path('inn_search/<inn>/', views.inn_search_view, name='inn_search'),

	path('help/', TemplateView.as_view(template_name='other_pages/help.html'), name='help'),
	path('about_us/', TemplateView.as_view(template_name='other_pages/about_us.html'), name='about_us'),
	path('city_selection/', views.city_selection_view, name='city'),

	path('policy/platform', TemplateView.as_view(template_name='other_pages/policy/platform.html'), name='platform'),
	path('policy/privacy', TemplateView.as_view(template_name='other_pages/policy/privacy.html'), name='privacy'),
	path('policy/service', TemplateView.as_view(template_name='other_pages/policy/service.html'), name='service'),
	path('policy/p_data', TemplateView.as_view(template_name='other_pages/policy/p_data.html'), name='p_data'),
	path('policy/', TemplateView.as_view(template_name='other_pages/privacy_policy.html'), name='policy'),

	path('create_product/', views.create_product_view),

	path(
		'become_company_fail/',
		TemplateView.as_view(
			template_name='account_pages/become_company_fail.html'
		),
		name='become_company_fail'),

	path(
		'delete_product_in_cart/<product_id>/',
		views.delete_product_in_cart_view,
		name='delete_product_in_cart'
	),

	path(
		'password_reset/',
		PasswordResetView.as_view(
			template_name='account_pages/password_reset.html',
			email_template_name='account_pages/password_reset_body.txt',
			subject_template_name='account_pages/password_reset_subject.txt'
		),
		name='password_reset'
	),

	path(
		'password_reset_done/',
		PasswordResetDoneView.as_view(
			template_name='account_pages/password_reset_done.html',
		),
		name='password_reset_done'
	),

	path(
		'password_reset_confirm/<uidb64>/<token>/',
		PasswordResetConfirmView.as_view(
			template_name='account_pages/password_reset_confirm.html',
			success_url='/login/'
		),
		name='password_reset_confirm'
	),

	path(
		'password_change/',
		PasswordChangeView.as_view(
			template_name='account_pages/password_change.html',
			success_url='/personal_account/'
		),
		name='password_change'
	),

	path(
		'logout/',
		LogoutView.as_view(),
		{'next_page': settings.LOGOUT_REDIRECT_URL},
		name='logout'
	),

	path(
		'account/register/',
		RegistrationView.as_view(form_class=CustomUserForm),
		name='register'
	),

	path('account/', include('django_registration.backends.activation.urls')),
]

printoplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from phonenumber_field.modelfields import PhoneNumberField


class UserManager(BaseUserManager):
	def create_user(
		self, email, first_name, last_name, is_receiving_news,
		is_company, phone_number, company_name, addresses, password=None
	):

		if not email:
			raise ValueError('У пользователя должен быть адрес электронной почты')

		user = self.model(
			email=self.normalize_email(email),
			first_name=first_name,
			last_name=last_name,
			phone_number=phone_number,
			company_name=company_name,
			addresses=addresses,
			is_receiving_news=is_receiving_news,
			is_company=is_company
		)
		user.set_password(password)
		user.save(using=self._db)

		return user

	def create_superuser(self, email, password=None):
		user = self.create_user(
			email,
			first_name='Admin',
			last_name='',
			phone_number='',
			company_name='',
			addresses=[],
			is_receiving_news=False,
			is_company=False,
			password=password
		)
		user.is_admin = True
		user.is_active = True
		user.save(using=self._db)

		return user


class User(AbstractBaseUser):
	"""Базовый класс всех пользователей"""
	email = models.EmailField(
		verbose_name='Email',
		max_length=255,
		unique=True
	)
	first_name = models.CharField(
		verbose_name='Имя',
		max_length=32
	)
	last_name = models.CharField(
		verbose_name='Фамилия',
		max_length=32
	)
	phone_number = PhoneNumberField(
		verbose_name='Номер телефона',
		max_length=12,
		blank=True,
	)
	company_name = models.CharField(
		verbose_name='Название компании',
		max_length=64,
		blank=True
	)
	addresses = models.JSONField()
	order_id = models.IntegerField(blank=True, null=True)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_receiving_news = models.BooleanField(default=False)
	is_company = models.BooleanField(default=False)
	is_active = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	def email_user(self, subject, message, from_email=None, **kwargs):
		"""Send an email to this user."""
		send_mail(subject, message, from_email, [self.email], **kwargs)

	def full_name(self):
		return '%s %s' % (self.last_name, self.first_name)

	def __str__(self):
		return self.first_name

	def has_perm(self, perm, obj=None):
		return True

	def has_perms(self, perm_list, obj=None):
		for perm in perm_list:
			if perm == 'is_auth' and not self.is_authenticated:
				return False
			if perm == 'is_admin' and not self.is_admin:
				return False
			if perm == 'is_company' and not self.is_company:
				return False
			if perm == 'is_not_company' and self.is_company:
				return False
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin


class Company(models.Model):
	"""Пользователь-исполнитель — данные о компании предоставляемой продукцию"""
	user = models.OneToOneField('User', on_delete=models.CASCADE)
	addresses = ArrayField(
		models.CharField(max_length=256),
		size=None,
		verbose_name='Список адресов'
	)
	inn = models.CharField(
		verbose_name='ИНН',
		max_length=12
	)
	logo = models.FileField(
		verbose_name='Логотип',
		upload_to='company_logos/',
		max_length=50,
		blank=True
	)
	company_files = models.FileField(
		verbose_name='Документы',
		upload_to='company_files/',
		max_length=50,
		blank=True
	)
	moderator_message = models.CharField(
		verbose_name='Сообщение для пользователя',
		max_length=256,
		blank=True
	)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_verification = models.BooleanField(default=False)
	is_verified = models.BooleanField(default=False)

	objects = models.Manager()


class Product(models.Model):
	"""Базовое описание продукта предоставляемого сайтом"""
	slug = models.SlugField(
		max_length=32,
		unique=True
	)
	name = models.CharField(
		verbose_name='Название',
		max_length=32
	)
	CATEGORY = (
		(1, 'Продукция с переплётом'),
		(2, 'Флаеры, открытки и плакаты'),
		(3, 'Календари'),
		(4, 'Офисное'),
		(5, 'Рекламная'),
		(6, 'Для гастрономии и событий'),
	)
	category = models.IntegerField(choices=CATEGORY)
	description = models.CharField(
		verbose_name='Описание',
		max_length=256
	)
	price = models.IntegerField()

	objects = models.Manager()

	def __str__(self):
		return self.name


class ProductCompany(models.Model):
	"""Продукт предоставляемый пользователем-исполнителем(компанией) на основе базового продукта"""
	company = models.ForeignKey(
		'Company',
		verbose_name='Компания',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		verbose_name='Продукт',
		on_delete=models.CASCADE
	)
	price = models.JSONField(verbose_name='Цены на продукт')
	characteristics = models.JSONField(verbose_name='Характеристики')

	objects = models.Manager()


class ShoppingCart(models.Model):
	"""Продукты находящиеся в корзине конкретного пользователя"""
	user = models.ForeignKey(
		'User',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		on_delete=models.CASCADE
	)
	characteristics = models.JSONField()
	design = models.FileField(
		upload_to='design_product/',
		max_length=50
	)
	other_design = ArrayField(
		models.FileField(
			upload_to='design_product/',
			max_length=50
		),
		size=None,
	)
	count = models.IntegerField()

	objects = models.Manager()


class ProductCharacteristics(models.Model):
	"""Список характеристик и их значений для конкретного продукта"""
	product = models.OneToOneField('Product', verbose_name='Продукт', on_delete=models.CASCADE)

	format = models.JSONField(verbose_name='Формат', null=True)
	color = models.JSONField(verbose_name='Цвет', null=True)
	material = models.JSONField(verbose_name='Материал', null=True)
	rounding = models.JSONField(verbose_name='Скругление', null=True)
	adhesive_side = models.JSONField(verbose_name='Клейкая сторона', null=True)
	sheets_count = models.JSONField(verbose_name='Количество листов', null=True)
	sheets_arrangement = models.JSONField(verbose_name='Расположение листов', null=True)
	protective_film = models.JSONField(verbose_name='Защитная плёнка', null=True)
	spiral_color = models.JSONField(verbose_name='Цвет спирали', null=True)
	finishing = models.JSONField(verbose_name='Отделка', null=True)
	paper = models.JSONField(verbose_name='Бумага', null=True)

	objects = models.Manager

	def __str__(self):
		return self.product.__str__()


class Order(models.Model):
	"""Базовая модель заказа"""
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	price = models.IntegerField(verbose_name='Общая стоимость')

	objects = models.Manager


class OrderDetail(models.Model):
	"""Детальное описание заказа после его оформления"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	address_and_deadline = models.JSONField(verbose_name='Адреса доставки и сроки')
	comment = models.CharField(
		verbose_name='Комментарий',
		max_length=1024,
		blank=True
	)
	datetime = models.DateTimeField(auto_now_add=True)
	STATUS = (
		(0, 'Формирование заказа'),
		(1, 'Новый заказ'),
		(2, 'Ожидания взятия в работу'),
		(3, 'Взят в работу'),
		(4, 'Ожидание подтверждения'),
		(5, 'Исполнен'),
		(6, 'Удалён')
	)
	status = models.IntegerField(choices=STATUS)

	objects = models.Manager


class OrderProduct(models.Model):
	"""Продукты фигурирующие в заказе"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	product = models.ForeignKey('Product', on_delete=models.CASCADE)
	characteristics = models.JSONField(verbose_name='Характеристики')
	design_url = models.CharField(verbose_name='Ссылка на дизайн', max_length=128)
	other_design_url = ArrayField(models.CharField(max_length=128), size=None)
	total_count = models.IntegerField(verbose_name='Общее количество товара')
	price = models.IntegerField(verbose_name='Стоимость')
	# {'ID_адреса': Количество, ...}
	count_and_address = models.JSONField(verbose_name='Адреса доставки и количество товара')

	objects = models.Manager


class OrderExecutionProposal(models.Model):
	"""Предложения от компаний на выполнение заказа"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	# {'ID_продукта': (Количество, ID_адреса, Цена), ...}
	order_products = models.JSONField()
	price = models.IntegerField(verbose_name='Общая стоимость предложения')
	is_paid = models.BooleanField(verbose_name='Статус оплаты для размещения предложения', default=False)
	is_partially = models.BooleanField(verbose_name='Частичное выполнение', default=False)

	objects = models.Manager


class OrderProposalTemp(models.Model):
	"""Временное сохранение списка предложений"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	proposal = models.JSONField()
	count = models.IntegerField(verbose_name='Количество предложений на один заказ')

	objects = models.Manager


class OrderExecution(models.Model):
	"""Заказ на выполнение компанией каторую выбрал заказчик"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	order_products = models.JSONField()
	STATUS = (
		(2, 'Отправлен на исполнение'),
		(3, 'Взят в работу'),
		(4, 'Подтверждение получения'),
		(5, 'Исполнен'),
		(6, 'Отменён')
	)
	status = models.IntegerField(choices=STATUS)
	price = models.IntegerField(verbose_name='Стоимость')

	objects = models.Manager


class OldOrder(models.Model):
	"""Информация о недействующих заказах"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	price = models.IntegerField()
	CONTEXT = (
		(1, 'Завершён'),
		(2, 'Окончание срока'),
		(3, 'Отмена компанией'),
		(4, 'Отмена клиентом'),
	)
	context = models.IntegerField(choices=CONTEXT)

core/templates/account_pages/admin_panel.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Панель администратора{% endblock %}
{% block content %}
<!-- Admin panel -->
<div>
	<div class="container pt-5" style="min-height: 76vh;">
		<h3 class="text-secondary ml-3">Панель администратора</h3>
		<div class="p-5">
			{% for company in company_list %}
			<div class="mb-3">
				<a class="text-secondary" data-toggle="collapse" href="#collapseExample{{ company.user.id }}" role="button" aria-expanded="false" aria-controls="collapseExample{{ company.user.id }}">
					{% if company.user.company_name %}{{ company.user.company_name }}{% else %}Без названия{% endif %} <span class="badge badge-pill badge-secondary pl-2">05.09.2020 14:30</span>
				</a>
				<div class="collapse" id="collapseExample{{ company.user.id }}">
					<div class="p-3">
						<dl class="row">
							<dt class="col-sm-3">ИНН</dt>
							<dd class="col-sm-9">{{ company.inn }}</dd>

							<dt class="col-sm-3">ОГРН</dt>
							<dd class="col-sm-9">8797878</dd>

							<dt class="col-sm-3">Адрес</dt>
							<dd class="col-sm-9">
								{% for address in company.addresses %}
								<p class="m-0">{{ address }}</p>
								{% endfor %}
							</dd>

							<dt class="col-sm-3">Телефон</dt>
							<dd class="col-sm-9">{{ company.user.phone_number }}</dd>

							<dt class="col-sm-3">Email</dt>
							<dd class="col-sm-9">{{ company.user.email }}</dd>

							<dt class="col-sm-3">Документы</dt>
							<dd class="col-sm-9"><a href="https://disk.yandex.ru/client/disk/files_company/{{ company.id }}">Ссылка</a></dd>
						</dl>
						<div class="mt-4">
							<form method="post">
								{% csrf_token %}
								<input type="hidden" name="next" value="">
								<input type="hidden" name="company_user" value="{{ company.user.email }}">

								<div id="div_id_moderator_message" class="form-group">
									<label for="id_moderator_message" class="">Сообщение для пользователя</label>
									<div class="">
										<input type="text" name="moderator_message" class="textinput textInput form-control" id="id_moderator_message">
									</div>
								</div>

								<div class="form-group">
									<div id="div_id_is_verification" class="form-check">
										<input type="checkbox" name="is_verification" class="checkboxinput form-check-input" id="id_is_verification">
										<label for="id_is_verification" class="form-check-label">Верифицировать пользователя</label>
									</div>
								</div>

								<button type="submit" class="btn btn-primary">Отправить</button>
							</form>
						</div>
					</div>
				</div>
			</div>
			{% empty %}
			<h3 class="text-center text-secondary my-4">Заявок нету!</h3>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

core/templates/account_pages/become_company.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Стать исполнителем{% endblock %}
{% block content_class %}bg-light h-100-60{% endblock %}
{% block content %}
<!-- Login form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Стать исполнителем</h3>
		</div>
		<div class="d-flex justify-content-center" >
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<form method="post" class="w-16rem" enctype="multipart/form-data">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ next }}">

					<div id="div_id_inn" class="form-group">
						<label for="id_inn" class=" requiredField">
							ИНН<span class="asteriskField">*</span>
						</label>
						<div>
							<input type="number" name="inn" min="0" maxlength="12" class="textinput textInput form-control inn-input" required="" id="id_inn"
										 style="
										 -webkit-inner-spin-button {
										 		-webkit-appearance: none;
										 }">
						</div>
						<button class="btn btn-outline-my btn-sm mt-2" onclick="search_inn()" type="button">Поиск</button>
					</div>

					<div id="div_id_company_name" class="form-group">
						<label for="id_company_name">
							Название компании<span class="asteriskField">*</span>
						</label>
						<div class="">
							<input type="text" name="company_name" maxlength="64"
										 class="textinput textInput form-control"
										 id="id_company_name" value="{{ request.user.company_name }}">
						</div>
					</div>

					<div id="div_id_phone_number" class="form-group">
						<label for="id_phone_number">
							Номер телефона<span class="asteriskField">*</span>
						</label>
						<div class="">
							<input type="tel" name="phone_number" maxlength="12"
										 class="textinput textInput form-control" id="id_phone_number"
										 value="{{ request.user.phone_number }}">
						</div>
					</div>

					<div id="div_id_company_files" class="form-group">
						<label for="id_company_files">
                Документы<span class="asteriskField">*</span>
            </label>
						<div>
							<input type="file" name="company_files" class="clearablefileinput form-control-file"
										 id="id_company_files" accept=".pdf">
						</div>
						<small class="form-text text-muted">Прикрепите юридические документы для верификации аккаунта.</small>
						<small class="form-text text-muted">Добавте всё в один PDF-файл.</small>
						<div class="mt-3">
							{% for error in form.company_files.errors %}
							<small class="mt-1 text-danger">{{ error|escape }}</small>
							{% endfor %}
						</div>
					</div>

					<div class="row px-3 mt-4">
						<a href="/personal_account/" class="btn btn-outline-my">Назад</a>
						<button type="submit" class="btn btn-primary ml-auto">Отправить</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/account_pages/become_company_fail.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}

{% block title %}PrintoPlace - Стать исполнителем - Ошибка{% endblock %}
{% block content_class %}bg-light h-100-60{% endblock %}
{% block content %}
<!-- Login form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Стать исполнителем</h3>
		</div>
		<div class="d-flex justify-content-center" >
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<div class="text-center text-secondary">
					<h6>Приносим свои извинения!</h6>
					<h6>В данный момент это функция не работает, пожалуйста, попробуйте позже.</h6>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/account_pages/login.html
{% extends 'base_templates.html' %}

{% block title %}PrintoPlace - Вход{% endblock %}
{% block content_class %}bg-light h-100-60{% endblock %}
{% block content %}
<!-- Login form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Вход</h3>
		</div>
		<div class="d-flex justify-content-center" >
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<form method="post" class="w-16rem">
					{% csrf_token %}
					<input type="hidden" name="next" value="">

					<div id="div_id_username" class="form-group">
						<label for="id_username" class=" requiredField">Email<span class="asteriskField">*</span></label>
						<div class="">
							<input type="text" name="username" autofocus="" autocapitalize="none"
										 autocomplete="username" maxlength="255"
										 class="textinput textInput form-control {% if form.username.errors %}is-invalid{% endif %}"
										 value="{% if form.username.value and not form.username.errors %}{{ form.username.value }}{% endif %}"
										 required="" id="id_username">
						</div>
						{% for error in form.username.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_password" class="form-group mb-0">
						<label for="id_password" class=" requiredField">Пароль<span class="asteriskField">*</span></label>
						<div class="">
							<input type="password" name="password" autocomplete="current-password"
										 class="textinput textInput form-control {% if form.password.errors %}is-invalid{% endif %}"
										 required="" id="id_password">
						</div>
						{% for error in form.password.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>

					<a href="{% url 'password_reset' %}" class="text-secondary">Забыли пароль?</a>

					{% for message in form.non_field_errors %}
					<p class="my-2 text-danger">Email или пароль введены неправильно</p>
					{% endfor %}

					<div class="row px-3 mt-4">
						<a href="{% url 'register' %}" class="btn btn-primary">Регистрация</a>
						<button type="submit" class="btn btn-primary ml-auto">Вход</button>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/account_pages/password_change.html
{% extends 'base_templates.html' %}

{% block title %}PrintoPlace - Новый пароль{% endblock %}
{% block content_class %}bg-light h-100-60{% endblock %}
{% block content %}
<!-- Login form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Новый пароль</h3>
		</div>
		<div class="d-flex justify-content-center" >
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<form method="post" class="w-16rem">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ next }}">

					<div id="div_id_old_password" class="form-group">
						<label for="id_old_password" class=" requiredField">Старый пароль<span class="asteriskField">*</span></label>
						<div>
							<input type="password" name="old_password" autocomplete="current-password" autofocus=""
										 class="textinput textInput form-control {% if form.old_password.errors %}is-invalid{% endif %}"
										 required="" id="id_old_password">
						</div>
						{% for error in form.old_password.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_new_password1" class="form-group">
						<label for="id_new_password1" class=" requiredField">Новый пароль<span class="asteriskField">*</span></label>
						<div>
							<input type="password" name="new_password1" autocomplete="new-password"
										 class="textinput textInput form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
										 required="" id="id_new_password1">
						</div>
						{% for error in form.new_password1.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>


					<div id="div_id_new_password2" class="form-group">
						<label for="id_new_password2" class=" requiredField">Подтверждение пароля<span class="asteriskField">*</span></label>
						<div>
							<input type="password" name="new_password2" autocomplete="new-password"
										 class="textinput textInput form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
										 required="" id="id_new_password2">
						</div>
						{% for error in form.new_password2.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>

					<div class="row px-3 mt-4">
						<a href="{% url 'personal_account' %}" class="btn btn-outline-my">Назад</a>
						<button type="submit" class="btn btn-primary ml-auto">Сменить пароль</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

core/templates/account_pages/password_reset.html
{% extends 'base_templates.html' %}

{% block title %}PrintoPlace - Восстановление пароля{% endblock %}
{% block content_class %}bg-light h-100-60{% endblock %}
{% block content %}
<!-- Login form -->
<div class="py-5">
	<div class="container">
		<div class="text-center mb-4">
			<h3>Восстановление пароля</h3>
		</div>
		<div class="d-flex justify-content-center" >
			<div class="d-inline-flex p-4 bd-highlight rounded border bg-white">
				<form method="post" class="w-16rem">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ next }}">

					<p class="text-secondary text-center">
						Введите почту которую вы использовали при регистрации.<br>
						На неё вам придёт ссылка для восстановление пароля.
					</p>

					<div id="div_id_email" class="form-group">
						<label for="id_email" class=" requiredField">Email<span class="asteriskField">*</span></label>
						<div>
							<input type="email" name="email" autofocus="" autocapitalize="none"
										 autocomplete="email" maxlength="255"
										 class="textinput textInput form-control {% if form.username.errors %}is-invalid{% endif %}"
										 required="" id="id_email">
						</div>
						{% for error in form.username.errors %}
						<p class="mt-1 text-danger">{{ error|escape }}</p>
						{% endfor %}
					</div>

					<div class="row px-3 mt-4">
						<a href="{% url 'login' %}" class="btn btn-outline-my">Назад</a>
						<button type="submit" class="btn btn-primary ml-auto">Отправить</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}