core/urls.py
from django.conf import settings
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import (
	PasswordResetConfirmView,
	PasswordResetDoneView,
	PasswordChangeView,
	PasswordResetView,
	LogoutView
)

from .forms import CustomUserForm
from core import views

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('products/', views.ProductListView.as_view(), name='products'),
	path('product/<slug:slug>/', views.ProductPageView.as_view(), name='one_product'),
	path('add_product/<slug:slug>/', views.AddProductView.as_view(), name='add_product'),
	path('add_product_list/', views.AddProductListView.as_view(), name='add_product_list'),
	path('personal_account/', views.PersonalAccountView.as_view(), name='personal_account'),
	path('product_update/<product_id>/', views.ProductUpdateView.as_view(), name='product_update'),
	path('proposals/<order_id>/', views.OrderExecutionProposalView.as_view(), name='proposals'),
	path('become_company/', views.BecomeCompanyView.as_view(), name='become_company'),
	path('update_company/', views.BecomeCompanyView.as_view(), name='update_company'),
	path('shopping_cart/', views.ShoppingCartView.as_view(), name='shopping_cart'),
	path('admin_panel/', views.AdminPanelView.as_view(), name='admin_panel'),
	path('new_orders/', views.NewOrdersView.as_view(), name='new_orders'),
	path('orders/', views.OrdersListView.as_view(), name='orders'),
	path('login/', views.LoginView.as_view(), name='login'),

	path('ordering/', views.OrderingView.as_view(), name='ordering'),
	path('product_distribution/', views.ProductDistributionView.as_view(), name='product_distribution'),
	path('order_handler/<ord_exec_id>/', views.set_order_status_view, name='order_handler'),
	path('cancel_order/<order_id>/<context>/', views.cancel_order_view, name='cancel_order'),
	path('delete_notification/', views.delete_notification_view, name='delete_notification'),
	path('choose_offer/<order_id>/<offer>/', views.choose_offer_view, name='choose_offer'),
	path('split_order/<order_id>/<offer>/', views.split_order_view, name='split_order'),
	path('repeat_order/<order_id>/', views.repeat_order_view, name='repeat_order'),
	path('payment/<order_id>/', views.PaymentView.as_view(), name='payment'),
	path('inn_search/<inn>/', views.inn_search_view, name='inn_search'),

	path('help/', TemplateView.as_view(template_name='other_pages/help.html'), name='help'),
	path('about_us/', TemplateView.as_view(template_name='other_pages/about_us.html'), name='about_us'),
	path('city_selection/', views.city_selection_view, name='city'),

	path('policy/platform', TemplateView.as_view(template_name='other_pages/policy/platform.html'), name='platform'),
	path('policy/privacy', TemplateView.as_view(template_name='other_pages/policy/privacy.html'), name='privacy'),
	path('policy/service', TemplateView.as_view(template_name='other_pages/policy/service.html'), name='service'),
	path('policy/p_data', TemplateView.as_view(template_name='other_pages/policy/p_data.html'), name='p_data'),
	path('policy/', TemplateView.as_view(template_name='other_pages/privacy_policy.html'), name='policy'),

	path('create_product/', views.create_product_view),

	path(
		'become_company_fail/',
		TemplateView.as_view(
			template_name='account_pages/become_company_fail.html'
		),
		name='become_company_fail'),

	path(
		'delete_product_in_cart/<product_id>/',
		views.delete_product_in_cart_view,
		name='delete_product_in_cart'
	),

	path(
		'password_reset/',
		PasswordResetView.as_view(
			template_name='account_pages/password_reset.html',
			email_template_name='account_pages/password_reset_body.txt',
			subject_template_name='account_pages/password_reset_subject.txt'
		),
		name='password_reset'
	),

	path(
		'password_reset_done/',
		PasswordResetDoneView.as_view(
			template_name='account_pages/password_reset_done.html',
		),
		name='password_reset_done'
	),

	path(
		'password_reset_confirm/<uidb64>/<token>/',
		PasswordResetConfirmView.as_view(
			template_name='account_pages/password_reset_confirm.html',
			success_url='/login/'
		),
		name='password_reset_confirm'
	),

	path(
		'password_change/',
		PasswordChangeView.as_view(
			template_name='account_pages/password_change.html',
			success_url='/personal_account/'
		),
		name='password_change'
	),

	path(
		'logout/',
		LogoutView.as_view(),
		{'next_page': settings.LOGOUT_REDIRECT_URL},
		name='logout'
	),

	path(
		'account/register/',
		RegistrationView.as_view(form_class=CustomUserForm),
		name='register'
	),

	path('account/', include('django_registration.backends.activation.urls')),
]

printoplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from phonenumber_field.modelfields import PhoneNumberField


class UserManager(BaseUserManager):
	def create_user(
		self, email, first_name, last_name, is_receiving_news,
		is_company, phone_number, company_name, addresses, password=None
	):

		if not email:
			raise ValueError('У пользователя должен быть адрес электронной почты')

		user = self.model(
			email=self.normalize_email(email),
			first_name=first_name,
			last_name=last_name,
			phone_number=phone_number,
			company_name=company_name,
			addresses=addresses,
			is_receiving_news=is_receiving_news,
			is_company=is_company
		)
		user.set_password(password)
		user.save(using=self._db)

		return user

	def create_superuser(self, email, password=None):
		user = self.create_user(
			email,
			first_name='Admin',
			last_name='',
			phone_number='',
			company_name='',
			addresses=[],
			is_receiving_news=False,
			is_company=False,
			password=password
		)
		user.is_admin = True
		user.is_active = True
		user.save(using=self._db)

		return user


class User(AbstractBaseUser):
	"""Базовый класс всех пользователей"""
	email = models.EmailField(
		verbose_name='Email',
		max_length=255,
		unique=True
	)
	first_name = models.CharField(
		verbose_name='Имя',
		max_length=32
	)
	last_name = models.CharField(
		verbose_name='Фамилия',
		max_length=32
	)
	phone_number = PhoneNumberField(
		verbose_name='Номер телефона',
		max_length=12,
		blank=True,
	)
	company_name = models.CharField(
		verbose_name='Название компании',
		max_length=64,
		blank=True
	)
	addresses = models.JSONField()
	order_id = models.IntegerField(blank=True, null=True)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_receiving_news = models.BooleanField(default=False)
	is_company = models.BooleanField(default=False)
	is_active = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	def email_user(self, subject, message, from_email=None, **kwargs):
		"""Send an email to this user."""
		send_mail(subject, message, from_email, [self.email], **kwargs)

	def full_name(self):
		return '%s %s' % (self.last_name, self.first_name)

	def __str__(self):
		return self.first_name

	def has_perm(self, perm, obj=None):
		return True

	def has_perms(self, perm_list, obj=None):
		for perm in perm_list:
			if perm == 'is_auth' and not self.is_authenticated:
				return False
			if perm == 'is_admin' and not self.is_admin:
				return False
			if perm == 'is_company' and not self.is_company:
				return False
			if perm == 'is_not_company' and self.is_company:
				return False
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin


class Company(models.Model):
	"""Пользователь-исполнитель — данные о компании предоставляемой продукцию"""
	user = models.OneToOneField('User', on_delete=models.CASCADE)
	addresses = ArrayField(
		models.CharField(max_length=256),
		size=None,
		verbose_name='Список адресов'
	)
	inn = models.CharField(
		verbose_name='ИНН',
		max_length=12
	)
	logo = models.FileField(
		verbose_name='Логотип',
		upload_to='company_logos/',
		max_length=50,
		blank=True
	)
	company_files = models.FileField(
		verbose_name='Документы',
		upload_to='company_files/',
		max_length=50,
		blank=True
	)
	moderator_message = models.CharField(
		verbose_name='Сообщение для пользователя',
		max_length=256,
		blank=True
	)
	notification = models.CharField(
		verbose_name='Уведомление',
		max_length=256,
		blank=True
	)
	is_verification = models.BooleanField(default=False)
	is_verified = models.BooleanField(default=False)

	objects = models.Manager()


class Product(models.Model):
	"""Базовое описание продукта предоставляемого сайтом"""
	slug = models.SlugField(
		max_length=32,
		unique=True
	)
	name = models.CharField(
		verbose_name='Название',
		max_length=32
	)
	CATEGORY = (
		(1, 'Продукция с переплётом'),
		(2, 'Флаеры, открытки и плакаты'),
		(3, 'Календари'),
		(4, 'Офисное'),
		(5, 'Рекламная'),
		(6, 'Для гастрономии и событий'),
	)
	category = models.IntegerField(choices=CATEGORY)
	description = models.CharField(
		verbose_name='Описание',
		max_length=256
	)
	price = models.IntegerField()

	objects = models.Manager()

	def __str__(self):
		return self.name


class ProductCompany(models.Model):
	"""Продукт предоставляемый пользователем-исполнителем(компанией) на основе базового продукта"""
	company = models.ForeignKey(
		'Company',
		verbose_name='Компания',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		verbose_name='Продукт',
		on_delete=models.CASCADE
	)
	price = models.JSONField(verbose_name='Цены на продукт')
	characteristics = models.JSONField(verbose_name='Характеристики')

	objects = models.Manager()


class ShoppingCart(models.Model):
	"""Продукты находящиеся в корзине конкретного пользователя"""
	user = models.ForeignKey(
		'User',
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product',
		on_delete=models.CASCADE
	)
	characteristics = models.JSONField()
	design = models.FileField(
		upload_to='design_product/',
		max_length=50
	)
	other_design = ArrayField(
		models.FileField(
			upload_to='design_product/',
			max_length=50
		),
		size=None,
	)
	count = models.IntegerField()

	objects = models.Manager()


class ProductCharacteristics(models.Model):
	"""Список характеристик и их значений для конкретного продукта"""
	product = models.OneToOneField('Product', verbose_name='Продукт', on_delete=models.CASCADE)

	format = models.JSONField(verbose_name='Формат', null=True)
	color = models.JSONField(verbose_name='Цвет', null=True)
	material = models.JSONField(verbose_name='Материал', null=True)
	rounding = models.JSONField(verbose_name='Скругление', null=True)
	adhesive_side = models.JSONField(verbose_name='Клейкая сторона', null=True)
	sheets_count = models.JSONField(verbose_name='Количество листов', null=True)
	sheets_arrangement = models.JSONField(verbose_name='Расположение листов', null=True)
	protective_film = models.JSONField(verbose_name='Защитная плёнка', null=True)
	spiral_color = models.JSONField(verbose_name='Цвет спирали', null=True)
	finishing = models.JSONField(verbose_name='Отделка', null=True)
	paper = models.JSONField(verbose_name='Бумага', null=True)

	objects = models.Manager

	def __str__(self):
		return self.product.__str__()


class Order(models.Model):
	"""Базовая модель заказа"""
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	price = models.IntegerField(verbose_name='Общая стоимость')

	objects = models.Manager


class OrderDetail(models.Model):
	"""Детальное описание заказа после его оформления"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	address_and_deadline = models.JSONField(verbose_name='Адреса доставки и сроки')
	comment = models.CharField(
		verbose_name='Комментарий',
		max_length=1024,
		blank=True
	)
	datetime = models.DateTimeField(auto_now_add=True)
	STATUS = (
		(0, 'Формирование заказа'),
		(1, 'Новый заказ'),
		(2, 'Ожидания взятия в работу'),
		(3, 'Взят в работу'),
		(4, 'Ожидание подтверждения'),
		(5, 'Исполнен'),
		(6, 'Удалён')
	)
	status = models.IntegerField(choices=STATUS)

	objects = models.Manager


class OrderProduct(models.Model):
	"""Продукты фигурирующие в заказе"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	product = models.ForeignKey('Product', on_delete=models.CASCADE)
	characteristics = models.JSONField(verbose_name='Характеристики')
	design_url = models.CharField(verbose_name='Ссылка на дизайн', max_length=128)
	other_design_url = ArrayField(models.CharField(max_length=128), size=None)
	total_count = models.IntegerField(verbose_name='Общее количество товара')
	price = models.IntegerField(verbose_name='Стоимость')
	# {'ID_адреса': Количество, ...}
	count_and_address = models.JSONField(verbose_name='Адреса доставки и количество товара')

	objects = models.Manager


class OrderExecutionProposal(models.Model):
	"""Предложения от компаний на выполнение заказа"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	# {'ID_продукта': (Количество, ID_адреса, Цена), ...}
	order_products = models.JSONField()
	price = models.IntegerField(verbose_name='Общая стоимость предложения')
	is_paid = models.BooleanField(verbose_name='Статус оплаты для размещения предложения', default=False)
	is_partially = models.BooleanField(verbose_name='Частичное выполнение', default=False)

	objects = models.Manager


class OrderProposalTemp(models.Model):
	"""Временное сохранение списка предложений"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	proposal = models.JSONField()
	count = models.IntegerField(verbose_name='Количество предложений на один заказ')

	objects = models.Manager


class OrderExecution(models.Model):
	"""Заказ на выполнение компанией каторую выбрал заказчик"""
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	order_products = models.JSONField()
	STATUS = (
		(2, 'Отправлен на исполнение'),
		(3, 'Взят в работу'),
		(4, 'Подтверждение получения'),
		(5, 'Исполнен'),
		(6, 'Отменён')
	)
	status = models.IntegerField(choices=STATUS)
	price = models.IntegerField(verbose_name='Стоимость')

	objects = models.Manager


class OldOrder(models.Model):
	"""Информация о недействующих заказах"""
	order = models.OneToOneField('Order', on_delete=models.CASCADE)
	price = models.IntegerField()
	CONTEXT = (
		(1, 'Завершён'),
		(2, 'Окончание срока'),
		(3, 'Отмена компанией'),
		(4, 'Отмена клиентом'),
	)
	context = models.IntegerField(choices=CONTEXT)

core/templates/product_pages/one_product.html
{% extends 'base_templates.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}PrintoPlace - {{ product.name }}{% endblock %}

{% block content %}
<!-- Settings product -->
<div class="bg-light py-5">
	<div class="container">
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input type="hidden" name="next" value="">
			<div class="row">
				<div class="col-12 col-md-8">
					<div id="div-design-1" style="display: block;">
						<div class="mx-auto" id="design-1" style="height: 355px; width: 252px;">
							<div class="mt-5" id="load_file-1" style="
									height: 355px;
									width: 252px;
									background-image: url(/static/image/cal-2.svg);
									background-repeat: no-repeat;">
								<div class="design bg-white" style="height: 355px;"></div>
							</div>
						</div>

						<div class="d-flex justify-content-center p-3 mt-3">
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" disabled><i class="fas fa-angle-left"></i></button>
							<p class="text-secondary my-auto mx-3">Обложка</p>
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(2, 1)">
								<i class="fas fa-angle-right"></i>
							</button>
						</div>

						<div class="bg-white rounded p-3 mt-3">
							<div class="custom-file">
								<input type="file" name="design" class="custom-file-input" onchange="handle_files(this.files, 1)" required>
								<label class="custom-file-label" id="label-1" data-browse="Загрузить">Загрузить оформление</label>
							</div>
							<div class="pt-2">
								<a class="text-secondary" href="https://yadi.sk/d/0csN12NBusKSTA?w=1"><i class="fas fa-external-link-alt"></i> Шаблоны</a>
							</div>
						</div>
					</div>

					<div id="div-design-2" style="display: none;">
						<div class="mx-auto" id="design-2" style="height: 355px; width: 252px;">
							<div class="mt-5" id="load_file-2" style="
									height: 355px;
									width: 252px;
									background-image: url(/static/image/cal-2.svg);
									background-repeat: no-repeat;">
								<div class="design bg-white" style="height: 355px;"></div>
							</div>
						</div>

						<div class="d-flex justify-content-center p-3 mt-3">
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(1, 2)">
								<i class="fas fa-angle-left"></i>
							</button>
							<p class="text-secondary my-auto mx-3">1 стр</p>
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(3, 2)">
								<i class="fas fa-angle-right"></i>
							</button>
						</div>

						<div class="bg-white rounded p-3 mt-3">
							<div class="custom-file">
								<input type="file" name="design" class="custom-file-input" onchange="handle_files(this.files, 2)">
								<label class="custom-file-label" id="label-2" data-browse="Загрузить">Загрузить оформление</label>
							</div>
							<div class="pt-2">
								<a class="text-secondary" href="https://yadi.sk/d/0csN12NBusKSTA?w=1"><i class="fas fa-external-link-alt"></i> Шаблоны</a>
							</div>
						</div>
					</div>

					<div id="div-design-3" style="display: none;">
						<div class="mx-auto" id="design-3" style="height: 355px; width: 252px;">
							<div class="mt-5" id="load_file-3" style="
									height: 355px;
									width: 252px;
									background-image: url(/static/image/cal-2.svg);
									background-repeat: no-repeat;">
								<div class="design bg-white" style="height: 355px;"></div>
							</div>
						</div>

						<div class="d-flex justify-content-center p-3 mt-3">
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(2, 3)">
								<i class="fas fa-angle-left"></i>
							</button>
							<p class="text-secondary my-auto mx-3">2 стр</p>
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(4, 3)">
								<i class="fas fa-angle-right"></i>
							</button>
						</div>

						<div class="bg-white rounded p-3 mt-3">
							<div class="custom-file">
								<input type="file" name="design" class="custom-file-input" onchange="handle_files(this.files, 3)">
								<label class="custom-file-label" id="label-3" data-browse="Загрузить">Загрузить оформление</label>
							</div>
							<div class="pt-2">
								<a class="text-secondary" href="https://yadi.sk/d/0csN12NBusKSTA?w=1"><i class="fas fa-external-link-alt"></i> Шаблоны</a>
							</div>
						</div>
					</div>

					<div id="div-design-4" style="display: none;">
						<div class="mx-auto" id="design-4" style="height: 355px; width: 252px;">
							<div class="mt-5" id="load_file-4" style="
									height: 355px;
									width: 252px;
									background-image: url(/static/image/cal-2.svg);
									background-repeat: no-repeat;">
								<div class="design bg-white" style="height: 355px;"></div>
							</div>
						</div>

						<div class="d-flex justify-content-center p-3 mt-3">
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" onclick="set_design_page(3, 4)">
								<i class="fas fa-angle-left"></i>
							</button>
							<p class="text-secondary my-auto mx-3">3 стр</p>
							<button type="button" class="btn btn-outline-secondary rounded-circle rotate-btn" disabled><i class="fas fa-angle-right"></i></button>
						</div>

						<div class="bg-white rounded p-3 mt-3">
							<div class="custom-file">
								<input type="file" name="design" class="custom-file-input" onchange="handle_files(this.files, 4)">
								<label class="custom-file-label" id="label-4" data-browse="Загрузить">Загрузить оформление</label>
							</div>
							<div class="pt-2">
								<a class="text-secondary" href="https://yadi.sk/d/0csN12NBusKSTA?w=1"><i class="fas fa-external-link-alt"></i> Шаблоны</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-12 col-md-4 mt-3 mt-md-0">
					<div class="bg-white rounded text-secondary p-3">
						<div class="text-center"><h4>{{ product.name }}</h4></div>
						<div class="text-right display-4 py-3">{{ product.price }}р</div>
						<div class="row mt-3">
							{% for char in characteristic_list %}
							<div class="col-4 btn-group dropleft mb-3" >
								<a class="text-secondary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ char.0 }}</a>
								<div class="dropdown-menu p-4 text-muted" style="width: 600px;">
									<h5>{{ char.0 }}</h5>
									<p>У вас есть выбор - из 25 фиксированных форматов для Flyer plano. Или можете распланировать размер как хотите в свободном формате.</p>

									<p>Фиксированные форматы:</p>
									<p>DIN A3 = 297 x 420 мм и 420 x 297 мм</p>
									<p>DIN A4 = 210 x 297 мм и 297 x 210 мм</p>
									<p>DIN A5 = 148 x 210 мм и 210 x 148 мм</p>
									<p>DIN A6 = 105 x 148 мм и 148 x 105 мм</p>
									<p>DIN A7 = 74 x 105 мм и 105 x 74 мм</p>
									<p>DIN A8 = 52 x 74 мм и 74 x 52 мм</p>
									<p>длина DIN 99 = 99 x 210 и 210 x 99 мм</p>
									<p>длина DIN 100 = 100 x 210 и 210 x 100 мм</p>
									<p>DIN длинный 105 = 105 x 210 мм и 210 x 105 мм</p>
									<p>1/2 портретная A4 = 105 x 297 мм</p>

									<p>Квадрат : 210 x 210 мм, 148 x 148 мм,
									120 x 120 мм, 105 x 105 мм, 100 x 100 мм</p>

									<p>Размеры формата относятся к окончательному формату.</p>

									<p>Что касается наших бесплатных форматов, мы хотели бы отметить,
										что по причинам, связанным с производством, не все комбинации длины и высоты могут быть реализованы.
										Если ваш свободный формат содержит такую ​​комбинацию, наш мастер подсказок поможет вам,
										и вы сможете изменить значения там.</p>

									<p>Также обратите внимание на допуск под обрез , который необходимо добавить к размерам.</p>
								</div>
							</div>
							<div class="col-8">
								<select name="{{ char.0 }}" class="select form-control form-control-sm mt-2 mt-md-0">
								{% for char_value_list in char.1.items %}
									{% for char_value in char_value_list.1 %}
									<option value="{{ char_value }}">{{ char_value }}</option>
									{% endfor %}
								{% endfor %}
								</select>
							</div>
							{% endfor %}
						</div>

						<div class="form-group mt-3">
							<label for="id_count" class=" requiredField">Количество</label>
							<div class="row">
								<div id="div_id_count" class="col-6 mb-3">
									<input type="number" name="count" min="1" class="numberinput form-control" placeholder="Количество" value="1" required id="id_count">
								</div>

								<div class="col-6 pl-0">
									<button class="btn btn-primary w-100" type="submit">В корзину</button>
								</div>
							</div>
						</div>
						<div class="row mt-3">
							<h5 class="col-6">ИТОГО:</h5>
							<h5 class="col-6 text-right">924p</h5>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

<!-- Product description -->
<div class="pt-5">
	<div class="container">
		<h3 class="text-secondary mb-3">Описание продукта</h3>
		<div class="pb-5 text-secondary text-center">
			<p>{{ product.description }}</p>
		</div>
	</div>
</div>

<!-- More product -->
<div class="bg-light">
	<div class="container py-4">
		<h3 class="text-secondary mb-4">Другие продукты</h3>
		<div class="row text-center">
			{% for one_prod in products %}
			{% url 'one_product' one_prod.slug as product_path %}
			<div class="col-6 col-md-3 col-lg-2">
				<a href="{{ product_path }}" class="text-secondary display-3 px-auto">
					<img src="{% get_static_prefix %}image/icon/{{ one_prod.slug }}.svg" width="130px" style="filter: brightness(.95); ">
				</a>
				<h5 class="text-secondary"><small>{{ one_prod.name }}</small></h5>
			</div>
			{% empty %}
			<h3 class="text-center text-secondary my-4">Ничего не найдено!</h3>
			{% endfor %}
			<div class="col-6 col-md-3 col-lg-2">
				<a href="{% url 'products' %}" class="text-secondary display-3 px-auto">
					<img src="{% get_static_prefix %}image/more_icon.svg" width="130px" style="filter: brightness(.95); ">
				</a>
				<h5 class="text-primary"><small>Больше товаров</small></h5>
			</div>
		</div>
	</div>
</div>

<!-- Product gallery -->
<!--<div class="bg-light py-5">-->
<!--	<div class="container">-->
<!--		<h3 class="text-secondary mb-5">Галерея продукта</h3>-->
<!--		<div class="row">-->

<!--			{% load static %}-->
<!--			<div class="col-12 col-md-4 pb-5">-->
<!--				<div class="card">-->
<!--					<img src="{% static 'image/Galereya_1.png' %}" class="card-img-top">-->
<!--					<div class="card-body">-->
<!--						<h5 class="card-title">Card title</h5>-->
<!--						<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->

<!--			<div class="col-12 col-md-4 pb-5">-->
<!--				<div class="card">-->
<!--					<img src="{% static 'image/Galereya_1.png' %}" class="card-img-top">-->
<!--					<div class="card-body">-->
<!--						<h5 class="card-title">Card title</h5>-->
<!--						<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->

<!--			<div class="col-12 col-md-4 pb-5">-->
<!--				<div class="card">-->
<!--					<img src="{% static 'image/Galereya_1.png' %}" class="card-img-top">-->
<!--					<div class="card-body">-->
<!--						<h5 class="card-title">Card title</h5>-->
<!--						<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->

{% include 'includes/contact_info.html' %}

{% include 'includes/delivery_payment.html' %}

{% include 'includes/footer.html' %}

<!-- Successful model -->
<div class="modal fade show" id="successful_model"
		 style="display: none; background-color: rgba(0, 0, 0, 0.5);">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
				<h3 class="text-center text-primary my-3"><i class="fas fa-shopping-cart"></i></h3>
				<h4 class="text-center mb-5">Товар добавлен в корзину!</h4>
				<div class="d-flex px-3">
					<a href="/shopping_cart/" class="btn btn-primary">Перейти в корзину</a>
					<a href="/products/" class="btn btn-primary ml-auto">Продолжить покупки</a>
				</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}